JWK_AddonsIntegrationsConfig {
 m_aAddons {
  JWK_AddonConfig "{2606C001C000000D}" {
   m_sGUID "24CF08C3D4AB8386"
   m_sLabel "FF_WW2_Wehrmacht"
   m_sVersion "1.0.0"
   m_rConfig "{0DE960A971B2D80C}Configs/Addons/FF_WW2_Wehrmacht.conf"
  }
  JWK_AddonConfig "{6988ECD1863F997D}" {
   m_sGUID "5F04139AD86CE1E6"
   m_sLabel "OperationOverlordAxisGear"
   m_sVersion "1.0.61"
   m_rConfig "{9DB39D47BB87BDBC}Configs/Addons/OperationOverlordAxisGear.conf"
  }
  JWK_AddonConfig "{2607A001E0000001}" {
   m_sGUID "3D433BEECA85F915"
   m_sLabel "FF_WW2_USArmy"
   m_sVersion "1.0.0"
   m_rConfig "{2607A001A0000003}Configs/Addons/FF_WW2_USArmy.conf"
  }
  JWK_AddonConfig "{2608A001E0000001}" {
   m_sGUID "52EF40DD004F8C93"
   m_sLabel "FF_WW2_RedArmy"
   m_sVersion "1.0.0"
   m_rConfig "{2608A001A0000003}Configs/Addons/FF_WW2_RedArmy.conf"
  }
 }
}
