SCR_Faction : "{B122E3B10BB3404B}Configs/Factions/OPFOR.conf" {
 FactionKey "RED_ARMY"
 UIInfo SCR_FactionUIInfo "{2608A001B0000001}" {
  Name "Red Army"
  Description "Рабоче-крестьянская Красная армия (1941-1945)"
 }
 "Identity of soldiers" FactionIdentity "{2608A001B0000002}" {
  VisualIdentityArray {
   VisualIdentity "{2608A001B0000003}" {
    Head "{143245D81F2BAB94}Prefabs/Characters/Heads/Head_White_10.et"
    Body "{0023F898C0FF18AA}Prefabs/Characters/Basebody/CharacterBasebody.et"
   }
   VisualIdentity "{2608A001B0000004}" {
    Head "{F8D5277F7C8C8F92}Prefabs/Characters/Heads/Head_White_11.et"
    Body "{0023F898C0FF18AA}Prefabs/Characters/Basebody/CharacterBasebody.et"
   }
   VisualIdentity "{2608A001B0000005}" {
    Head "{6FD8A2D1B7AAFEAE}Prefabs/Characters/Heads/Head_White_12.et"
    Body "{0023F898C0FF18AA}Prefabs/Characters/Basebody/CharacterBasebody.et"
   }
  }
  SocialIdentity SocialIdentity "{2608A001B0000006}" {
   NamesConfig {
    "Ivan" "Vladimir" "Sergei" "Mikhail" "Nikolai" "Andrei" "Dmitri" "Aleksandr"
    "Pyotr" "Boris" "Yuri" "Viktor" "Leonid" "Anatoly" "Pavel" "Roman"
    "Stanislav" "Igor" "Oleg" "Valery" "Gennady" "Vasily" "Semyon" "Konstantin"
    "Maxim" "Lev" "Vyacheslav" "Arkadiy" "Yefim" "Fyodor"
   }
  }
 }
}
