SCR_Faction : "{B122E3B10BB3404B}Configs/Factions/OPFOR.conf" {
 FactionKey "US_WW2"
 m_sFactionFlag "{5EE4E278D8EF2466}Assets/Flag textures/Flag_1_2_USMilitary_BCR.edds"
 UIInfo SCR_FactionUIInfo "{2607A001B0000001}" {
  Name "US Army"
  Description "United States Army (1941-1945) — GI & 101st Airborne"
  Icon "{5EE4E278D8EF2466}Assets/Flag textures/Flag_1_2_USMilitary_BCR.edds"
 }
 "Identity of soldiers" FactionIdentity "{2607A001B0000002}" {
  VisualIdentityArray {
   VisualIdentity "{2607A001B0000003}" {
    Head "{143245D81F2BAB94}Prefabs/Characters/Heads/Head_White_10.et"
    Body "{0023F898C0FF18AA}Prefabs/Characters/Basebody/CharacterBasebody.et"
   }
   VisualIdentity "{2607A001B0000004}" {
    Head "{F8D5277F7C8C8F92}Prefabs/Characters/Heads/Head_White_11.et"
    Body "{0023F898C0FF18AA}Prefabs/Characters/Basebody/CharacterBasebody.et"
   }
   VisualIdentity "{2607A001B0000005}" {
    Head "{6FD8A2D1B7AAFEAE}Prefabs/Characters/Heads/Head_White_12.et"
    Body "{0023F898C0FF18AA}Prefabs/Characters/Basebody/CharacterBasebody.et"
   }
  }
  SocialIdentity SocialIdentity "{2607A001B0000006}" {
   NamesConfig {
    "John" "James" "Robert" "William" "David" "Richard" "Charles" "Thomas"
    "Michael" "Joseph" "Frank" "George" "Harold" "Walter" "Ralph" "Eugene"
    "Bobby" "Jack" "Eddie" "Tommy" "Hank" "Donald" "Edward" "Henry"
    "Patrick" "Leonard" "Stanley" "Vincent" "Wallace" "Russell"
   }
  }
 }
}
