JWK_FactionConfig {
 m_sFactionKey "CIV"
 m_sCustomName "Civils"
 m_CommonTrait JWK_CommonFactionTrait "{668F43F42C2008B8}" : "{410CE2A8225A03D1}Configs/Factions/SharedTraits/BaseTrait_Common.conf" {
  m_aLanguages {
   FRENCH
  }
 }
 m_AmbientRoleTrait JWK_AmbientRoleFactionTrait "{668F43F42AC04070}" : "{88EE5EA90BCB4DB4}Configs/Factions/RoleTraits/BaseTrait_AmbientRole.conf" {
  m_aVehicles {
   "{62B4A8E40D31F94B}Prefabs/Vehicles/Wheeled/WW2_Bike/WW2_Bike_base.et"
  }
  m_aVehiclesEntityCatalogImports {
   JWK_BaseResourceNameFilter "{C91F4FE946AF94D0}" {
    m_sLabel "block_modern"
    m_sPrefabNameExcludeFilter {
     "*"
    }
   }
  }
  m_Loadout JWK_LoadoutConfig "{668F43F48D7F6304}" : "{596BAFA3AFB6E40A}Configs/Factions/Utils/Loadouts/Loadout_CIV.conf" {
  }
 }
}
